CREATE TABLE USUARIO(
    ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    NOME VARCHAR (150)  NOT NULL, 
    EMAIL VARCHAR (150)  NOT NULL, 
    SENHA VARCHAR (150)  NOT NULL, 
    TIPO_USER VARCHAR (150)  NOT NULL  
);
CREATE TABLE ENDERECO_DE_ENTREGA(
    ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    LOGRADOURO VARCHAR (150)  NOT NULL, 
    NUMERO INTEGER NOT NULL, 
    COMPLEMENTO VARCHAR (150),
    BAIRRO VARCHAR (150)  NOT NULL,
    CIDADE VARCHAR (150)  NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE RESTAURANTE(
    ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    LOGRADOURO VARCHAR (150)  NOT NULL, 
    NUMERO INTEGER NOT NULL, 
    COMPLEMENTO VARCHAR (150),
    BAIRRO VARCHAR (150)  NOT NULL,
    CIDADE VARCHAR (150)  NOT NULL,
    TIPO_COMIDA VARCHAR (150)  NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);


CREATE TABLE ITEM(
    ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    NOME VARCHAR (150)  NOT NULL, 
    TIPO INTEGER NOT NULL, 
    DESCRICAO VARCHAR (150),
    PRECO DOUBLE NOT NULL,
    DISPONIVEL BOOLEAN NOT NULL,
    PROMOCAO BOOLEAN NOT NULL,
    ID_RESTAURANTE INTEGER NOT NULL,
    FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID)
    
);


CREATE TABLE FUNCIONARIO(
    ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    ID_RESTAURANTE INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);


CREATE TABLE PEDIDO(
    ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    ESTADO VARCHAR (150)  NOT NULL, 
    DATA_PEDIDO DATE NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE ITEM_PEDIDO(
    ID INTEGER  PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    ID_PEDIDO INTEGER NOT NULL,
    ID_ITEM INTEGER NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
    FOREIGN KEY (ID_ITEM) REFERENCES ITEM(ID)
);


INSERT INTO usuario(nome,email,senha, tipo_user) values('yan', 'yan@yan.com', 'yan','Gerente');
INSERT INTO usuario(nome,email,senha, tipo_user) values('yan', 'yan2@yan.com', 'yan','Cliente');
INSERT INTO usuario(nome,email,senha, tipo_user) values('yan', 'yan3@yan.com', 'yan','ChefeDeCozinha');
INSERT INTO usuario(nome,email,senha, tipo_user) values('yan', 'yan4@yan.com', 'yan','Entregador');